apiVersion: apps/v1
kind: Deployment
metadata:
  name: rento-backend
  labels:
    app: rento-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rento-backend
  template:
    metadata:
      labels:
        app: rento-backend
    spec:
      containers:
      - name: rento-backend
        image: rento-backend:latest
        ports:
        - containerPort: 5001
        envFrom:
        - secretRef:
            name: rento-backend-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rento-backend-service
spec:
  type: LoadBalancer
  selector:
    app: rento-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
    name: http
